'use client'
import { useState } from 'react'
import { Button, Modal } from '@heroui/react'
import { ShoppingBag, ArrowUpRight, Check, Laptop, Play, BookOpen } from 'lucide-react'
import Link from 'next/link'
import { useContent } from '@/hooks/useContent'
import { useCart } from '@/hooks/useCart'
import type { Product, Service, Course, Tip } from '@/lib/types'
import { serviceContent } from '@/lib/service-content'
import { money, productMessage, maintenanceMessage, repairMessage, courseMessage, tipMessage } from '@/lib/whatsapp'
import { WhatsAppLink } from './Site'
export function ContentState({loading,error,empty,reload}:{loading:boolean;error:string|null;empty:boolean;reload:()=>void}){if(loading)return <p role="status" className="empty-state">Cargando contenido…</p>;if(error)return <div role="alert" className="empty-state"><p>No pudimos cargar el contenido. {error}</p><Button onPress={reload}>Reintentar</Button></div>;if(empty)return <p className="empty-state">Todavía no hay contenido disponible. Consulta las novedades por WhatsApp.</p>;return null}
export function CatalogImage({src,alt,className=''}:{src?:string|null;alt:string;className?:string}){const [failed,setFailed]=useState(false);return src&&!failed?<img src={src} alt={alt} className={className} loading="lazy" onError={()=>setFailed(true)}/>:<div className={'image-fallback '+className}><Laptop size={48}/><span>{alt}</span></div>}
export function DetailModal({title,children,trigger='Ver detalles'}:{title:string;children:React.ReactNode;trigger?:string}){return <Modal><Button variant="ghost" className="detail-button">{trigger}<ArrowUpRight size={16}/></Button><Modal.Backdrop><Modal.Container size="lg" scroll="inside"><Modal.Dialog><Modal.CloseTrigger aria-label="Cerrar detalles"/><Modal.Header><Modal.Heading>{title}</Modal.Heading></Modal.Header><Modal.Body className="detail-body">{children}</Modal.Body></Modal.Dialog></Modal.Container></Modal.Backdrop></Modal>}
export function CategoryGrid(){const content=useContent('categories');return <><ContentState {...content} empty={!content.data.length}/><div className="category-grid">{content.data.map(c=><Link href={'/products?category='+encodeURIComponent(c.slug)} className="category-tile" key={c.id}><CatalogImage src={c.image_url} alt={c.name} className="category-image"/><strong>{c.name}</strong><ArrowUpRight size={15}/></Link>)}</div></>}
function AddProduct({product}:{product:Product}){const {addItem}=useCart();const [added,setAdded]=useState(false);return <><Button data-testid="add-to-cart" className="add-button" isDisabled={!product.in_stock} onPress={()=>{addItem(product);setAdded(true)}}>{added?<Check size={16}/>:<ShoppingBag size={16}/>} {product.in_stock?(added?'Agregado · agregar otro':'Agregar al carrito'):'No disponible'}</Button><span className="sr-only" role="status">{added?product.name+' agregado al carrito':''}</span></>}
export function ProductCard({product:p}:{product:Product}){return <article className="product-card" data-testid="product-card"><div className="product-photo"><CatalogImage src={p.image_url||p.images[0]} alt={p.name}/>{p.featured&&<span className="photo-tag">DESTACADO</span>}</div><div className="card-content"><p className="card-eyebrow">{p.brand||p.category}</p><h3>{p.name}</h3><p className="card-description">{p.description}</p><div className="price-row"><strong>{money(p.price)}</strong><span className={p.in_stock?'stock':'muted'}>{p.in_stock?'● Disponible':'Agotado'}</span></div><AddProduct product={p}/><DetailModal title={p.name}><div className="product-gallery">{Array.from(new Set([p.image_url,...p.images].filter(Boolean))).map(url=><CatalogImage key={url} src={url} alt={p.name}/>)}</div><p>{p.description}</p><dl className="specifications">{Object.entries(p.specifications).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><strong className="detail-price">{money(p.price)}</strong><AddProduct product={p}/><WhatsAppLink message={productMessage(p.name, p.price)}>Consultar producto por WhatsApp</WhatsAppLink></DetailModal></div></article>}
export function FeaturedProducts(){const c=useContent('products');const featured=c.data.filter(p=>p.featured);const data=(featured.length?featured:c.data).slice(0,4);return <><ContentState {...c} empty={!data.length}/><div className="product-grid">{data.map(p=><ProductCard key={p.id} product={p}/>)}</div>{c.mode==='demo'&&<p className="demo-note">Catálogo de demostración · Precios y disponibilidad sujetos a confirmación.</p>}</>}
function DetailList({title,items}:{title:string;items:string[]}){return <div><h3>{title}</h3><ul className="detail-list">{items.map((s,i)=><li key={i}><Check size={16}/><span>{s}</span></li>)}</ul></div>}
type ServiceKind = 'mantenimiento' | 'reparacion'
function equipmentSubject(title:string){const value=title.toLowerCase();if(value.includes('laptop'))return 'una Laptop';if(value.includes('pc / computadoras'))return 'una PC / Computadora';if(value.includes('impresora'))return 'una Impresora';if(value.includes('playstation'))return 'una PlayStation / Consola';if(value.includes('redes / routers'))return 'una red o un router';return 'otro equipo tecnológico'}
export function ServiceCard({service:s,kind}:{service:Service;kind:ServiceKind}){const maintenance=kind==='mantenimiento';const equipment=equipmentSubject(s.title);const preview=(maintenance?s.includes:s.problems).slice(0,5);const message=maintenance?maintenanceMessage(equipment):repairMessage(equipment);return <article className="editorial-card service-card" data-testid="service-card" data-service-kind={kind}><div className="editorial-photo"><CatalogImage src={s.image_url} alt={s.title}/><span className="photo-tag">{maintenance?'PREVENCIÓN':'DIAGNÓSTICO'}</span></div><div className="card-content"><p className="card-eyebrow">{maintenance?'CUIDADO TÉCNICO':'FALLAS FRECUENTES'}</p><h3>{s.title}</h3><p className="card-description">{s.description}</p><ul className="service-preview">{preview.map(item=><li key={item}><Check size={15}/><span>{item}</span></li>)}</ul><div className="service-actions"><DetailModal title={s.title}><CatalogImage src={s.image_url} alt={s.title} className="detail-photo"/><p>{s.description}</p>{maintenance?<><DetailList title="Qué incluye" items={s.includes}/><DetailList title="Problemas que ayuda a prevenir" items={s.problems}/><DetailList title="Recomendaciones" items={s.recommendations}/></>:<><DetailList title="Fallas frecuentes" items={s.problems}/><DetailList title="Síntomas frecuentes" items={s.includes}/><DetailList title="Posibles áreas a revisar" items={s.recommendations}/><p className="diagnosis-note">El origen exacto de una falla se determina mediante diagnóstico técnico.</p></>}<WhatsAppLink message={message}>{maintenance?'Consultar mantenimiento por WhatsApp':'Solicitar diagnóstico por WhatsApp'}</WhatsAppLink></DetailModal><WhatsAppLink message={message} className="service-whatsapp">{maintenance?'Consultar por WhatsApp':'Solicitar diagnóstico'}</WhatsAppLink></div></div></article>}
export function Services({limit,kind='reparacion'}:{limit?:number;kind?:ServiceKind}){const c=useContent('services');const remote=c.data.filter(service=>service.category===kind);const fallback=serviceContent.filter(service=>service.category===kind);const data=c.loading||c.error?[]:remote.length?remote:fallback;return <><ContentState {...c} empty={!c.loading&&!c.error&&!data.length}/><div className="service-grid" data-testid={`${kind}-grid`}>{data.slice(0,limit).map(service=><ServiceCard key={service.id} service={service} kind={kind}/>)}</div></>}
function courseDate(c:Course){return !c.start_date?'Próximamente':new Date(c.start_date+'T12:00:00').toLocaleDateString('es-EC',{day:'numeric',month:'long',year:'numeric'})}
export function CourseCard({course:c}:{course:Course}){return <article className="editorial-card" data-testid="course-card"><div className="editorial-photo"><CatalogImage src={c.image_url} alt={c.title}/><span className="photo-tag">{!c.start_date?'PRÓXIMAMENTE':c.status==='closed'?'CERRADO':'CAPACITACIÓN'}</span></div><div className="card-content"><p className="card-eyebrow">{c.level} · {c.modality}</p><h3>{c.title}</h3><p className="card-description">{c.description}</p><p className="course-meta"><BookOpen size={15}/> {c.duration} <span>{courseDate(c)}</span></p><DetailModal title={c.title} trigger="Explorar curso"><CatalogImage src={c.image_url} alt={c.title} className="detail-photo"/><p>{c.description}</p><dl className="specifications">{[['Nivel',c.level],['Modalidad',c.modality],['Duración',c.duration],['Fecha',courseDate(c)],['Horario',c.schedule||'Por confirmar'],['Cupos',c.seats===null?'Por confirmar':String(c.seats)],['Estado',c.status==='closed'?'Cerrado':c.status==='open'?'Inscripciones abiertas':'Próximamente']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><DetailList title="Temario" items={c.syllabus}/><WhatsAppLink message={courseMessage(c.title)}>Consultar / inscribirme por WhatsApp</WhatsAppLink></DetailModal></div></article>}
export function Courses({limit}:{limit?:number}){const c=useContent('courses');return <><ContentState {...c} empty={!c.data.length}/><div className="course-grid">{c.data.slice(0,limit).map(course=><CourseCard key={course.id} course={course}/>)}</div></>}
function videoSource(tip:Tip):{kind:'youtube'|'video'|'invalid'|'pending';url?:string}{let u:URL;try{u=new URL(tip.url)}catch{return {kind:'pending'}}if(u.protocol!=='https:')return {kind:'invalid'};if(tip.kind==='youtube'){const id=u.hostname==='youtu.be'?u.pathname.slice(1):['www.youtube.com','youtube.com','m.youtube.com'].includes(u.hostname)?(u.searchParams.get('v')||u.pathname.split('/').pop()):'';return id&&/^[a-zA-Z0-9_-]{11}$/.test(id)?{kind:'youtube',url:'https://www.youtube-nocookie.com/embed/'+id}:{kind:'invalid'}}if(tip.kind==='video'&&(/\.supabase\.co$/.test(u.hostname)||u.hostname==='res.cloudinary.com'))return {kind:'video',url:u.href};return {kind:'invalid'}}
function Video({tip}:{tip:Tip}){const source=videoSource(tip);if(source.kind==='youtube')return <iframe className="video-frame" src={source.url} title={tip.title} allowFullScreen loading="lazy" referrerPolicy="strict-origin-when-cross-origin"/>;if(source.kind==='video')return <video className="video-frame" src={source.url} controls preload="metadata"/>;return <p>{source.kind==='pending'?'Video pendiente de publicación.':'Video no disponible en un proveedor autorizado.'}</p>}
export function TipCard({tip:t}:{tip:Tip}){return <article className="editorial-card tip-card" data-testid="tip-card"><div className="editorial-photo"><CatalogImage src={t.image_url} alt={t.title}/>{t.kind!=='article'&&<span className="play-icon"><Play size={24}/></span>}</div><div className="card-content"><p className="card-eyebrow">{t.kind==='article'?'LECTURA': 'VIDEO'} · {t.category}</p><h3>{t.title}</h3><p className="card-description">{t.description}</p><DetailModal title={t.title} trigger={t.kind==='article'?'Leer consejo':'Ver video'}>{t.kind!=='article'&&<Video tip={t}/>}<p className="whitespace-pre-line">{t.content||t.description}</p><WhatsAppLink message={tipMessage(t.title)}>Consultar sobre este tip por WhatsApp</WhatsAppLink></DetailModal></div></article>}
export function Tips({limit}:{limit?:number}){const c=useContent('tips');return <><ContentState {...c} empty={!c.data.length}/><div className="course-grid">{c.data.slice(0,limit).map(t=><TipCard key={t.id} tip={t}/>)}</div></>}
