import Link from 'next/link'
import { ArrowUpRight, MessageCircle, MapPin, ArrowRight } from 'lucide-react'
import { whatsappUrl } from '@/lib/whatsapp'
export function WhatsAppLink({message,children,className=''}:{message:string;children:React.ReactNode;className?:string}){return <a className={'action whatsapp-action '+className} href={whatsappUrl(message)} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/>{children}</a>}
export function SectionHeading({eyebrow,title,description,href,label='Ver todos'}:{eyebrow:string;title:string;description?:string;href?:string;label?:string}){return <div className="section-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2>{description&&<p className="muted mt-3">{description}</p>}</div>{href&&<Link className="text-link" href={href}>{label}<ArrowRight size={17}/></Link>}</div>}
export function PageHeading({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <section className="page-heading"><div className="wrap"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div></section>}
export function AboutBlock(){return <section className="wrap section about-grid"><div className="local-photo"><img src="/images/local-ultratecno.jpeg" alt="Fachada real del establecimiento UltraTecno en Machala" loading="lazy"/><span><MapPin size={17}/> MACHALA, ECUADOR</span></div><div><p className="eyebrow">TECNOLOGÍA CON UN ROSTRO CERCANO</p><h2>Conoce UltraTecno</h2><p className="muted mt-5">Detrás de cada equipo hay algo importante: tu trabajo, tus estudios, tus ideas. Aquí encuentras productos, repuestos y servicio técnico para seguir adelante.</p><p className="muted mt-4">Visítanos en 10 de Agosto y 8va Norte, frente a la Ferretería Armijos. Conversemos sobre lo que necesitas.</p><Link className="action mt-7" href="/contact">Conoce nuestra ubicación<ArrowUpRight size={18}/></Link></div></section>}
export function ContactBanner(){return <section className="wrap contact-banner"><div><p className="eyebrow">ESTAMOS PARA AYUDARTE</p><h2>Tu próximo paso empieza<br/>con una conversación.</h2><p>Productos, reparaciones o cursos. Cuéntanos qué necesitas.</p></div><WhatsAppLink message="Hola UltraTecno, quisiera asesoría.">Hablemos por WhatsApp</WhatsAppLink></section>}
export function Footer(){return <footer className="site-footer"><div className="wrap footer-grid"><div><img src="/images/logo-ultratecno.png" alt="UltraTecno" width="215" height="63"/><p>Más allá de la Tecnología.<br/>Soluciones para tu mundo digital.</p></div><div><h3>Explora</h3><Link href="/products">Tienda</Link><Link href="/reparaciones">Servicio técnico</Link><Link href="/courses">Cursos y capacitaciones</Link><Link href="/consejos">Consejos y tips</Link></div><div><h3>Conócenos</h3><Link href="/quienes-somos">Quiénes Somos</Link><Link href="/contact">Contacto y ubicación</Link><Link href="/cart">Mi carrito</Link></div><div><h3>Estamos en Machala</h3><p>10 de Agosto y 8va Norte.<br/>Frente a la Ferretería Armijos.</p><a href={whatsappUrl('Hola UltraTecno.')} target="_blank" rel="noreferrer">+593 98 780 8181 ↗</a></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} UltraTecno</span><span>Tecnología. Conocimiento. Soluciones.</span></div></footer>}
