import type { Service } from './types';

const photo = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1200&q=85`;
const laptop = photo('photo-1496181133206-80ce9b88a853');
const computer = photo('photo-1591799264318-7e6ef8ddb7ea');
const printer = photo('photo-1612815154858-60aa4c59eaa6');
const consoleImage = photo('photo-1606813907291-d86efa9b94db');
const network = photo('photo-1558494949-ef010cbdcc31');
const electronics = photo('photo-1518770660439-4636190af475');

export const serviceContent = [
  {
    id: 'base-maintenance-laptop',
    title: 'Mantenimiento preventivo de Laptop',
    category: 'mantenimiento',
    image_url: laptop,
    description: 'Limpieza y revisión técnica para ayudar a conservar la refrigeración y el rendimiento de tu laptop.',
    includes: ['Desmontaje técnico cuando corresponda', 'Limpieza interna de polvo', 'Limpieza de placa', 'Limpieza de ventiladores', 'Limpieza de disipadores', 'Limpieza de rejillas', 'Limpieza de puertos', 'Cambio de pasta térmica', 'Revisión/cambio de pads térmicos cuando corresponda', 'Lubricación de ventilador cuando técnicamente sea aplicable', 'Revisión de temperaturas', 'Pruebas finales de funcionamiento'],
    problems: ['Sobrecalentamiento', 'Apagados por temperatura', 'Pérdida de rendimiento', 'Ruido excesivo del ventilador', 'Acumulación de polvo', 'Obstrucción del sistema de refrigeración', 'Degradación térmica'],
    recommendations: ['Realiza el servicio según el uso, ambiente y condición del equipo.', 'Respalda tus archivos antes de entregar el equipo.', 'El mantenimiento ayuda a prevenir problemas, pero no garantiza que nunca ocurran fallas.'],
    featured: true,
    active: true,
  },
  {
    id: 'base-maintenance-computer',
    title: 'Mantenimiento preventivo de PC / Computadoras',
    category: 'mantenimiento',
    image_url: computer,
    description: 'Cuidado interno de componentes y ventilación para ayudar a mantener temperaturas y funcionamiento estables.',
    includes: ['Limpieza interna', 'Limpieza de ventiladores', 'Limpieza de CPU', 'Limpieza de GPU', 'Limpieza de disipadores', 'Cambio de pasta térmica', 'Revisión de refrigeración', 'Revisión visual de fuente de poder', 'Limpieza de memorias RAM y slots', 'Revisión visual de cableado', 'Limpieza de filtros', 'Pruebas de temperatura', 'Pruebas finales'],
    problems: ['Sobrecalentamiento', 'Bajo rendimiento térmico', 'Ruido excesivo', 'Acumulación de polvo', 'Reinicios relacionados con temperatura', 'Obstrucción de ventilación'],
    recommendations: ['Mantén libres las entradas y salidas de aire.', 'Evita colocar la torre directamente sobre superficies con polvo.', 'El mantenimiento ayuda a prevenir problemas, pero no sustituye un diagnóstico cuando ya existe una falla.'],
    featured: true,
    active: true,
  },
  {
    id: 'base-maintenance-printer',
    title: 'Mantenimiento preventivo de Impresoras',
    category: 'mantenimiento',
    image_url: printer,
    description: 'Limpieza y comprobaciones ajustadas al modelo para cuidar la alimentación de papel y la calidad de impresión.',
    includes: ['Limpieza exterior', 'Limpieza interior accesible', 'Limpieza del sistema de alimentación de papel', 'Revisión de rodillos', 'Limpieza/revisión de cabezales según modelo', 'Prueba de inyectores cuando aplique', 'Revisión de calidad de impresión', 'Limpieza de residuos de tinta/polvo accesibles', 'Pruebas finales'],
    problems: ['Acumulación de residuos accesibles', 'Problemas de alimentación por suciedad', 'Pérdida gradual de calidad de impresión', 'Obstrucciones de inyectores cuando aplique', 'Desgaste prematuro por falta de cuidado'],
    recommendations: ['El procedimiento depende del modelo y de su condición.', 'No siempre corresponde desmontar completamente la impresora.', 'Utiliza consumibles y papel compatibles con las indicaciones del fabricante.'],
    featured: true,
    active: true,
  },
  {
    id: 'base-maintenance-console',
    title: 'Mantenimiento preventivo de PlayStation / Consolas',
    category: 'mantenimiento',
    image_url: consoleImage,
    description: 'Limpieza del sistema de ventilación y revisión térmica para ayudar a conservar el rendimiento de tu consola.',
    includes: ['Limpieza interna', 'Limpieza de ventilador', 'Limpieza de disipadores', 'Limpieza de rejillas', 'Cambio de pasta térmica cuando corresponda', 'Revisión de pads térmicos cuando corresponda', 'Limpieza de puertos', 'Revisión de temperatura', 'Pruebas finales'],
    problems: ['Sobrecalentamiento', 'Ruido excesivo del ventilador', 'Acumulación de polvo', 'Obstrucción de rejillas', 'Pérdida de rendimiento térmico'],
    recommendations: ['Ubica la consola en un espacio ventilado.', 'No bloquees sus rejillas ni la uses sobre textiles.', 'El mantenimiento ayuda a prevenir; una falla existente requiere diagnóstico.'],
    featured: false,
    active: true,
  },
  {
    id: 'base-maintenance-network',
    title: 'Mantenimiento preventivo de Redes / Routers',
    category: 'mantenimiento',
    image_url: network,
    description: 'Revisión física y funcional básica para cuidar la conectividad y detectar condiciones que pueden degradarla.',
    includes: ['Limpieza física', 'Revisión visual del equipo', 'Revisión de conectores', 'Revisión de cableado', 'Verificación básica de configuración', 'Revisión de cobertura Wi-Fi', 'Revisión de interferencias básicas', 'Verificación básica de DHCP', 'Pruebas de conectividad', 'Recomendaciones de ubicación'],
    problems: ['Cobertura deficiente por ubicación', 'Conectores flojos o deteriorados', 'Acumulación de polvo', 'Interferencias básicas', 'Problemas evitables de cableado'],
    recommendations: ['Mantén routers y access points ventilados.', 'Evita ocultarlos detrás de obstáculos densos.', 'Los problemas persistentes requieren diagnóstico de la red completa.'],
    featured: false,
    active: true,
  },
  {
    id: 'base-maintenance-other',
    title: '¿Tienes otro equipo tecnológico?',
    category: 'mantenimiento',
    image_url: electronics,
    description: 'UltraTecno puede revisar otros dispositivos y definir el mantenimiento adecuado después de una inspección.',
    includes: ['Inspección inicial del equipo', 'Identificación de partes accesibles', 'Definición del mantenimiento técnicamente aplicable', 'Presupuesto y alcance antes de intervenir'],
    problems: ['Acumulación de polvo', 'Ventilación deficiente', 'Desgaste prematuro por falta de cuidado'],
    recommendations: ['Cuéntanos qué equipo tienes y cómo lo utilizas.', 'El alcance se confirma después de inspeccionarlo.'],
    featured: false,
    active: true,
  },
  {
    id: 'base-repair-laptop',
    title: 'Fallas comunes en Laptops',
    category: 'reparacion',
    image_url: laptop,
    description: 'Diagnóstico técnico para laptops que presentan problemas de encendido, imagen, temperatura, carga o funcionamiento.',
    includes: ['No prende ningún indicador', 'Cargador conectado pero no responde', 'Intenta iniciar y se apaga', 'El LED enciende pero el equipo no arranca'],
    problems: ['No enciende', 'Enciende pero no da imagen', 'Se apaga repentinamente', 'Se sobrecalienta', 'Ventilador con ruido excesivo', 'No carga la batería', 'No reconoce el cargador', 'Pantalla con líneas', 'Pantalla sin iluminación', 'Teclado con fallas', 'Touchpad con problemas', 'Windows lento', 'Windows no inicia', 'Wi-Fi/Bluetooth con problemas', 'Puertos USB/HDMI con fallas'],
    recommendations: ['Alimentación', 'Cargador', 'Batería', 'Circuito de carga', 'Placa', 'Pantalla y cableado', 'Almacenamiento, memoria u otros componentes'],
    featured: true,
    active: true,
  },
  {
    id: 'base-repair-computer',
    title: 'Fallas comunes en PC / Computadoras',
    category: 'reparacion',
    image_url: computer,
    description: 'Evaluación de computadoras con fallas de arranque, estabilidad, temperatura, rendimiento o reconocimiento de componentes.',
    includes: ['No muestra imagen al encender', 'Se reinicia durante el uso', 'Windows muestra errores o no inicia', 'Los componentes no son reconocidos'],
    problems: ['No enciende', 'Enciende pero no da imagen', 'Reinicios inesperados', 'Pantallazos azules', 'Sobrecalentamiento', 'Ruido excesivo', 'Bajo rendimiento', 'No reconoce RAM', 'No reconoce discos', 'Problemas con fuente de poder', 'Windows no inicia', 'Problemas de red', 'Problemas de video'],
    recommendations: ['Fuente y alimentación', 'Memoria RAM', 'Almacenamiento', 'Tarjeta gráfica', 'Refrigeración', 'Placa y conexiones', 'Sistema operativo y controladores'],
    featured: true,
    active: true,
  },
  {
    id: 'base-repair-printer',
    title: 'Fallas comunes en Impresoras',
    category: 'reparacion',
    image_url: printer,
    description: 'Diagnóstico de problemas de impresión, papel, tinta, comunicación y calidad según el modelo de impresora.',
    includes: ['El trabajo queda en cola y no imprime', 'El papel no avanza o se atasca', 'La impresión sale incompleta o manchada', 'El equipo muestra códigos o alertas'],
    problems: ['No imprime', 'Impresión con líneas', 'Colores incorrectos', 'Hojas en blanco', 'No toma papel', 'Atascos frecuentes', 'Cabezal/inyección obstruida', 'No reconoce tinta/cartucho', 'Error de almohadillas cuando aplique', 'Problemas USB', 'Problemas Wi-Fi', 'Manchas en impresión', 'Calidad de impresión deficiente'],
    recommendations: ['Sistema de alimentación de papel', 'Rodillos y sensores accesibles', 'Cabezal o sistema de inyección según modelo', 'Consumibles', 'Conectividad USB/Wi-Fi', 'Contadores y componentes internos cuando aplique'],
    featured: true,
    active: true,
  },
  {
    id: 'base-repair-console',
    title: 'Fallas comunes en PlayStation / Consolas',
    category: 'reparacion',
    image_url: consoleImage,
    description: 'Diagnóstico para consolas con problemas de encendido, video, temperatura, almacenamiento, puertos o conectividad.',
    includes: ['No responde al botón de encendido', 'Enciende y se apaga', 'El televisor no recibe señal', 'Presenta alertas o fallas durante el juego'],
    problems: ['No enciende', 'No da imagen', 'Se apaga', 'Se sobrecalienta', 'Ventilador con ruido', 'Problemas HDMI', 'Problemas de almacenamiento', 'Problemas de conectividad', 'Problemas con controles', 'Problemas con puertos'],
    recommendations: ['Alimentación', 'Sistema térmico', 'Puerto y circuito HDMI', 'Almacenamiento', 'Conectividad', 'Puertos, controles u otros componentes'],
    featured: false,
    active: true,
  },
  {
    id: 'base-repair-network',
    title: 'Fallas comunes en Redes / Routers',
    category: 'reparacion',
    image_url: network,
    description: 'Revisión de problemas de conectividad, cobertura, direccionamiento, cableado y comunicación entre equipos de red.',
    includes: ['La conexión se pierde de forma intermitente', 'Algunos equipos no navegan', 'La señal no cubre las áreas esperadas', 'Routers o access points se reinician'],
    problems: ['Internet lento', 'Pérdida de conexión', 'Wi-Fi con poca cobertura', 'Equipos que no obtienen IP', 'Problemas DHCP', 'Interferencias', 'Cableado defectuoso', 'Conectores dañados', 'Router/AP con reinicios', 'Configuración incorrecta', 'Problemas entre router principal y Access Points'],
    recommendations: ['Router o access point', 'Fuente de alimentación', 'Configuración y DHCP', 'Canales e interferencias', 'Cableado y conectores', 'Topología y enlace entre equipos'],
    featured: false,
    active: true,
  },
  {
    id: 'base-repair-other',
    title: 'Otros problemas tecnológicos',
    category: 'reparacion',
    image_url: electronics,
    description: 'Si tu dispositivo presenta otra falla, podemos inspeccionarlo y definir qué pruebas técnicas corresponden.',
    includes: ['El equipo no funciona como antes', 'Presenta errores intermitentes', 'Tiene conectores o controles con problemas', 'No sabes cómo identificar el origen de la falla'],
    problems: ['Problemas de encendido', 'Fallas de funcionamiento', 'Errores de conectividad', 'Daños en puertos o conectores', 'Comportamiento intermitente'],
    recommendations: ['Alimentación', 'Conectividad', 'Controles y puertos', 'Componentes internos accesibles', 'Otras áreas definidas después de la inspección'],
    featured: false,
    active: true,
  },
] satisfies Service[];
