import type { Metadata } from 'next'
import Link from 'next/link'
import { notFound, permanentRedirect } from 'next/navigation'
import Navbar from '@/components/Navbar'
import StructuredData from '@/components/StructuredData'
import { AddProduct, CatalogImage } from '@/components/Catalog'
import { Footer, WhatsAppLink } from '@/components/Site'
import { getPublicCategories, getPublicProducts } from '@/lib/public-data'
import { absoluteUrl, productSlug, seoMetadata } from '@/lib/seo'
import { money, productMessage } from '@/lib/whatsapp'

type Props={params:Promise<{slug:string}>}
async function productFor(slug:string){const products=await getPublicProducts();return products.find(product=>productSlug(product)===slug)||products.find(product=>slug.endsWith(`-${String(product.id).toLowerCase()}`))}
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const product=await productFor(slug);if(!product)return {title:'Producto no encontrado',robots:{index:false,follow:false}};const description=product.description.slice(0,155);return seoMetadata({title:`${product.name} | UltraTecno`,description,path:`/productos/${productSlug(product)}`,image:product.image_url||product.images[0]})}
export default async function ProductPage({params}:Props){const {slug}=await params;const [product,categories]=await Promise.all([productFor(slug),getPublicCategories()]);if(!product)notFound();const canonicalPath=`/productos/${productSlug(product)}`;if(slug!==productSlug(product))permanentRedirect(canonicalPath);const category=categories.find(item=>item.slug===product.category);const images=Array.from(new Set([product.image_url,...product.images].filter(Boolean)));const structuredData={"@context":"https://schema.org","@type":"Product",name:product.name,image:images.map(absoluteUrl),description:product.description,...(product.brand?{brand:{"@type":"Brand",name:product.brand}}:{}),offers:{"@type":"Offer",url:absoluteUrl(canonicalPath),priceCurrency:'USD',price:Number(product.price).toFixed(2),availability:product.in_stock?'https://schema.org/InStock':'https://schema.org/OutOfStock'}};return <><StructuredData data={structuredData}/><Navbar/><main id="main"><section className="wrap section"><nav className="breadcrumbs" aria-label="Migas de pan"><Link href="/tienda">Tienda</Link><span>/</span>{category?<Link href={`/categoria/${category.slug}`}>{category.name}</Link>:<span>{product.category}</span>}</nav><article className="product-detail-grid"><div className="product-detail-gallery">{images.length?images.map((image,index)=><CatalogImage key={image} src={image} alt={index?`${product.name}, imagen ${index+1}`:product.name}/>):<CatalogImage alt={product.name}/>}</div><div className="product-detail-copy"><p className="eyebrow">{product.brand||category?.name||product.category}</p><h1>{product.name}</h1><p className="product-detail-description">{product.description}</p><div className="price-row product-detail-price"><strong>{money(product.price)}</strong><span className={product.in_stock?'stock':'muted'}>{product.in_stock?'● Disponible':'No disponible'}</span></div>{Object.keys(product.specifications).length>0&&<dl className="specifications">{Object.entries(product.specifications).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl>}<AddProduct product={product}/><WhatsAppLink message={productMessage(product.name,product.price)}>Consultar producto por WhatsApp</WhatsAppLink></div></article></section></main><Footer/></>}
