'use client'
import { Suspense } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import { Button } from '@heroui/react'
import Navbar from '@/components/Navbar'
import { useContent } from '@/hooks/useContent'
import { ProductCard, ContentState } from '@/components/Catalog'
import { PageHeading, Footer } from '@/components/Site'
function Catalog(){const params=useSearchParams();const router=useRouter();const c=useContent('products');const categories=useContent('categories');const q=params.get('q')||'';const category=params.get('category')||'';const stock=params.get('stock')==='1';const update=(key:string,value:string)=>{const p=new URLSearchParams(params.toString());if(value)p.set(key,value);else p.delete(key);router.replace('/products?'+p.toString(),{scroll:false})};const normalized=(text:string)=>text.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();const data=c.data.filter(p=>(!category||p.category===category)&&(!stock||p.in_stock)&&normalized(p.name+' '+p.description+' '+p.brand).includes(normalized(q)));return <><PageHeading eyebrow="TIENDA ULTRATECNO" title="Tecnología para lo que viene." description="Explora, elige y consulta tu compra directamente por WhatsApp."/><div className="wrap section catalog-layout"><aside className="catalog-filters"><h2>Categorías</h2><Button variant="ghost" className={!category?'selected-filter':''} onPress={()=>update('category','')}>Todos los productos</Button>{categories.data.map(cat=><Button variant="ghost" key={cat.id} className={category===cat.slug?'selected-filter':''} onPress={()=>update('category',cat.slug)}>{cat.name}</Button>)}<label className="stock-filter"><input type="checkbox" checked={stock} onChange={e=>update('stock',e.target.checked?'1':'')}/> Solo disponibles</label></aside><div><div className="catalog-toolbar"><label className="catalog-search"><span className="sr-only">Buscar en el catálogo</span><input value={q} placeholder="Buscar producto, marca o descripción…" onChange={e=>update('q',e.target.value)}/></label><span>{data.length} productos</span></div>{c.mode==='demo'&&<p className="demo-note mb-5">Catálogo de demostración. Confirma precio y disponibilidad antes de comprar.</p>}<ContentState {...c} empty={!data.length}/>{!c.loading&&!c.error&&!data.length&&<Button onPress={()=>router.replace('/products')}>Limpiar filtros</Button>}<div className="product-grid catalog-products">{data.map(p=><ProductCard key={p.id} product={p}/>)}</div></div></div></>}
export default function ProductsPage(){return <><Navbar/><main id="main"><Suspense fallback={<p role="status">Cargando tienda…</p>}><Catalog/></Suspense></main><Footer/></>}
