-- Additive base catalog for the existing services table. Apply only after the
-- application version that separates mantenimiento/reparacion is deployed.
begin;

with seed(title,category,image_url,description,includes,problems,recommendations,featured,active) as (
  values
  ('Mantenimiento preventivo de Laptop','mantenimiento','https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=85','Limpieza y revisión técnica para ayudar a conservar la refrigeración y el rendimiento de tu laptop.','["Desmontaje técnico cuando corresponda","Limpieza interna de polvo","Limpieza de placa","Limpieza de ventiladores","Limpieza de disipadores","Limpieza de rejillas","Limpieza de puertos","Cambio de pasta térmica","Revisión/cambio de pads térmicos cuando corresponda","Lubricación de ventilador cuando técnicamente sea aplicable","Revisión de temperaturas","Pruebas finales de funcionamiento"]'::jsonb,'["Sobrecalentamiento","Apagados por temperatura","Pérdida de rendimiento","Ruido excesivo del ventilador","Acumulación de polvo","Obstrucción del sistema de refrigeración","Degradación térmica"]'::jsonb,'["Realiza el servicio según el uso, ambiente y condición del equipo.","Respalda tus archivos antes de entregar el equipo.","El mantenimiento ayuda a prevenir problemas, pero no garantiza que nunca ocurran fallas."]'::jsonb,true,true),
  ('Mantenimiento preventivo de PC / Computadoras','mantenimiento','https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=1200&q=85','Cuidado interno de componentes y ventilación para ayudar a mantener temperaturas y funcionamiento estables.','["Limpieza interna","Limpieza de ventiladores","Limpieza de CPU","Limpieza de GPU","Limpieza de disipadores","Cambio de pasta térmica","Revisión de refrigeración","Revisión visual de fuente de poder","Limpieza de memorias RAM y slots","Revisión visual de cableado","Limpieza de filtros","Pruebas de temperatura","Pruebas finales"]'::jsonb,'["Sobrecalentamiento","Bajo rendimiento térmico","Ruido excesivo","Acumulación de polvo","Reinicios relacionados con temperatura","Obstrucción de ventilación"]'::jsonb,'["Mantén libres las entradas y salidas de aire.","Evita colocar la torre directamente sobre superficies con polvo.","El mantenimiento ayuda a prevenir problemas, pero no sustituye un diagnóstico cuando ya existe una falla."]'::jsonb,true,true),
  ('Mantenimiento preventivo de Impresoras','mantenimiento','https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=1200&q=85','Limpieza y comprobaciones ajustadas al modelo para cuidar la alimentación de papel y la calidad de impresión.','["Limpieza exterior","Limpieza interior accesible","Limpieza del sistema de alimentación de papel","Revisión de rodillos","Limpieza/revisión de cabezales según modelo","Prueba de inyectores cuando aplique","Revisión de calidad de impresión","Limpieza de residuos de tinta/polvo accesibles","Pruebas finales"]'::jsonb,'["Acumulación de residuos accesibles","Problemas de alimentación por suciedad","Pérdida gradual de calidad de impresión","Obstrucciones de inyectores cuando aplique","Desgaste prematuro por falta de cuidado"]'::jsonb,'["El procedimiento depende del modelo y de su condición.","No siempre corresponde desmontar completamente la impresora.","Utiliza consumibles y papel compatibles con las indicaciones del fabricante."]'::jsonb,true,true),
  ('Mantenimiento preventivo de PlayStation / Consolas','mantenimiento','https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=1200&q=85','Limpieza del sistema de ventilación y revisión térmica para ayudar a conservar el rendimiento de tu consola.','["Limpieza interna","Limpieza de ventilador","Limpieza de disipadores","Limpieza de rejillas","Cambio de pasta térmica cuando corresponda","Revisión de pads térmicos cuando corresponda","Limpieza de puertos","Revisión de temperatura","Pruebas finales"]'::jsonb,'["Sobrecalentamiento","Ruido excesivo del ventilador","Acumulación de polvo","Obstrucción de rejillas","Pérdida de rendimiento térmico"]'::jsonb,'["Ubica la consola en un espacio ventilado.","No bloquees sus rejillas ni la uses sobre textiles.","El mantenimiento ayuda a prevenir; una falla existente requiere diagnóstico."]'::jsonb,false,true),
  ('Mantenimiento preventivo de Redes / Routers','mantenimiento','https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=85','Revisión física y funcional básica para cuidar la conectividad y detectar condiciones que pueden degradarla.','["Limpieza física","Revisión visual del equipo","Revisión de conectores","Revisión de cableado","Verificación básica de configuración","Revisión de cobertura Wi-Fi","Revisión de interferencias básicas","Verificación básica de DHCP","Pruebas de conectividad","Recomendaciones de ubicación"]'::jsonb,'["Cobertura deficiente por ubicación","Conectores flojos o deteriorados","Acumulación de polvo","Interferencias básicas","Problemas evitables de cableado"]'::jsonb,'["Mantén routers y access points ventilados.","Evita ocultarlos detrás de obstáculos densos.","Los problemas persistentes requieren diagnóstico de la red completa."]'::jsonb,false,true),
  ('¿Tienes otro equipo tecnológico?','mantenimiento','https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=85','UltraTecno puede revisar otros dispositivos y definir el mantenimiento adecuado después de una inspección.','["Inspección inicial del equipo","Identificación de partes accesibles","Definición del mantenimiento técnicamente aplicable","Presupuesto y alcance antes de intervenir"]'::jsonb,'["Acumulación de polvo","Ventilación deficiente","Desgaste prematuro por falta de cuidado"]'::jsonb,'["Cuéntanos qué equipo tienes y cómo lo utilizas.","El alcance se confirma después de inspeccionarlo."]'::jsonb,false,true),
  ('Fallas comunes en Laptops','reparacion','https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1200&q=85','Diagnóstico técnico para laptops que presentan problemas de encendido, imagen, temperatura, carga o funcionamiento.','["No prende ningún indicador","Cargador conectado pero no responde","Intenta iniciar y se apaga","El LED enciende pero el equipo no arranca"]'::jsonb,'["No enciende","Enciende pero no da imagen","Se apaga repentinamente","Se sobrecalienta","Ventilador con ruido excesivo","No carga la batería","No reconoce el cargador","Pantalla con líneas","Pantalla sin iluminación","Teclado con fallas","Touchpad con problemas","Windows lento","Windows no inicia","Wi-Fi/Bluetooth con problemas","Puertos USB/HDMI con fallas"]'::jsonb,'["Alimentación","Cargador","Batería","Circuito de carga","Placa","Pantalla y cableado","Almacenamiento, memoria u otros componentes"]'::jsonb,true,true),
  ('Fallas comunes en PC / Computadoras','reparacion','https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=1200&q=85','Evaluación de computadoras con fallas de arranque, estabilidad, temperatura, rendimiento o reconocimiento de componentes.','["No muestra imagen al encender","Se reinicia durante el uso","Windows muestra errores o no inicia","Los componentes no son reconocidos"]'::jsonb,'["No enciende","Enciende pero no da imagen","Reinicios inesperados","Pantallazos azules","Sobrecalentamiento","Ruido excesivo","Bajo rendimiento","No reconoce RAM","No reconoce discos","Problemas con fuente de poder","Windows no inicia","Problemas de red","Problemas de video"]'::jsonb,'["Fuente y alimentación","Memoria RAM","Almacenamiento","Tarjeta gráfica","Refrigeración","Placa y conexiones","Sistema operativo y controladores"]'::jsonb,true,true),
  ('Fallas comunes en Impresoras','reparacion','https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?auto=format&fit=crop&w=1200&q=85','Diagnóstico de problemas de impresión, papel, tinta, comunicación y calidad según el modelo de impresora.','["El trabajo queda en cola y no imprime","El papel no avanza o se atasca","La impresión sale incompleta o manchada","El equipo muestra códigos o alertas"]'::jsonb,'["No imprime","Impresión con líneas","Colores incorrectos","Hojas en blanco","No toma papel","Atascos frecuentes","Cabezal/inyección obstruida","No reconoce tinta/cartucho","Error de almohadillas cuando aplique","Problemas USB","Problemas Wi-Fi","Manchas en impresión","Calidad de impresión deficiente"]'::jsonb,'["Sistema de alimentación de papel","Rodillos y sensores accesibles","Cabezal o sistema de inyección según modelo","Consumibles","Conectividad USB/Wi-Fi","Contadores y componentes internos cuando aplique"]'::jsonb,true,true),
  ('Fallas comunes en PlayStation / Consolas','reparacion','https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=1200&q=85','Diagnóstico para consolas con problemas de encendido, video, temperatura, almacenamiento, puertos o conectividad.','["No responde al botón de encendido","Enciende y se apaga","El televisor no recibe señal","Presenta alertas o fallas durante el juego"]'::jsonb,'["No enciende","No da imagen","Se apaga","Se sobrecalienta","Ventilador con ruido","Problemas HDMI","Problemas de almacenamiento","Problemas de conectividad","Problemas con controles","Problemas con puertos"]'::jsonb,'["Alimentación","Sistema térmico","Puerto y circuito HDMI","Almacenamiento","Conectividad","Puertos, controles u otros componentes"]'::jsonb,false,true),
  ('Fallas comunes en Redes / Routers','reparacion','https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1200&q=85','Revisión de problemas de conectividad, cobertura, direccionamiento, cableado y comunicación entre equipos de red.','["La conexión se pierde de forma intermitente","Algunos equipos no navegan","La señal no cubre las áreas esperadas","Routers o access points se reinician"]'::jsonb,'["Internet lento","Pérdida de conexión","Wi-Fi con poca cobertura","Equipos que no obtienen IP","Problemas DHCP","Interferencias","Cableado defectuoso","Conectores dañados","Router/AP con reinicios","Configuración incorrecta","Problemas entre router principal y Access Points"]'::jsonb,'["Router o access point","Fuente de alimentación","Configuración y DHCP","Canales e interferencias","Cableado y conectores","Topología y enlace entre equipos"]'::jsonb,false,true),
  ('Otros problemas tecnológicos','reparacion','https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=85','Si tu dispositivo presenta otra falla, podemos inspeccionarlo y definir qué pruebas técnicas corresponden.','["El equipo no funciona como antes","Presenta errores intermitentes","Tiene conectores o controles con problemas","No sabes cómo identificar el origen de la falla"]'::jsonb,'["Problemas de encendido","Fallas de funcionamiento","Errores de conectividad","Daños en puertos o conectores","Comportamiento intermitente"]'::jsonb,'["Alimentación","Conectividad","Controles y puertos","Componentes internos accesibles","Otras áreas definidas después de la inspección"]'::jsonb,false,true)
)
insert into public.services(title,category,image_url,description,includes,problems,recommendations,featured,active)
select seed.* from seed
where not exists (
  select 1 from public.services current
  where current.category=seed.category and current.title=seed.title
);

commit;
